### ISSUE TITLE
Parted and partprobe no-longer available in Chrome OS

### ISSUE THREAD

**Issue by omgmog** [omgmog/archarm-usb-hp-chromebook-11#14] opened 2014-10-31 16:33 UTC
... but `partx` is available.

Exploring solutions to do this without `parted` or `partprobe`

Edit: if you're using `4537` you can find `parted` and `partprobe` in `/usr/sbin`, I've got updated instructions [below](#issuecomment-65443635)

**Comment by jman6495** [comment] 2015-02-16 14:55
May have found something interesting regarding this.
From dev mode there is a dev_install command that installs a package manager and a load of extras, i'm running it now, it may install parted :) i'll keep you all updated !

**Comment by jman6495** [comment] 2015-02-16 14:59
@starkers @omgmog by running the following in shell from dev mode we can get parted & partprobe back: 
sudo su
dev_install
emerge parted

**Comment by omgmog** [comment] 2015-02-16 15:03
Might be time to overhaul the whole process!

**Comment by omgmog** [comment] 2015-02-16 15:03
http://www.chromium.org/chromium-os/how-tos-and-troubleshooting/install-software-on-base-images

**Comment by elkhunter** [comment] 2015-02-16 15:15
Has anyone been able to boot from USB on a SPRING G9A-D3I-A2A device?   I've tried the USB image posted here (on multiple devices) as well as rolling back to the older version of chromium as mentioned above and ran the script from there to create a USB stick but everytime I try booting from USB I get the same error output posted by @duck above.

**Comment by jman6495** [comment] 2015-02-16 17:48
ok so i've been playing around with it and theres some issue. Running 
> sudo dev_install
fails to install all the python libs for some reason, so nothing works properly.
I think this must be because the sudo doesn't apply to one of the subscripts in dev_install.
When i Run
> sudo su -
First, the it's not an issue at all. It installs successfully.
Same issue if i don't  run the command before installing things

**Comment by starkers** [comment] 2015-02-16 23:59
Thanks for the updates chaps...

I ran through it all again but without much luck booting again

Found a small error with install.sh which I'll do a PR against now

```dev_install``` was fun but I have absolutely no interest in learning more about ChromeOS lol

Boot on my G9B-D3C-A42
![SPRING G9B-D3C-A42](https://cloud.githubusercontent.com/assets/462087/6221176/92450c70-b637-11e4-8a95-6d4d62291b09.jpg)

**Comment by jman6495** [comment] 2015-02-17 02:14
I'll be commiting a fix for a couple of problems in a moment, when I have done so @starkers redownload the script and try this :
from your chromebooks terminal run : 
> sudo su -
> dev_install
Respond No to the dev_install question (when it offers to install everything)
then (still as root) run : 
> emerge parted
once you've done this run the script. DO Not let your chromebooks screen turn off, for some reason this causes USB drives to remount. And makes a bloody mess.
I've also noticed that chromeos enjoys remounting freshly repartitioned things. This creates an issue where by the disk is already mounted when the script tries to mount it, so it fails to.
I'm working on a fix atm.
There is also an issue with the systemd fix (of my creating) whereby the disk does not remount properly, i am fixing this by mounting it with exec rights in the first place.
If it can remain averagly minimal i'll also add the whole parted installation procedure (perhaps in a seperate script first, to be discussed ! ) in a future commit :)

**Comment by jman6495** [comment] 2015-02-18 21:36
@duck @starkers I believe the issue described is caused by #26 !

**Comment by starkers** [comment] 2015-02-18 22:37
Having a look now, doesn't explain why a dd imaged stick failed to boot though

**Comment by jman6495** [comment] 2015-02-18 23:53
Custom cgpt solves it ! I'll push a fix ASAP :D :)

**Comment by jman6495** [comment] 2015-02-19 16:02
Question : If i can get the partprobe and parted binaries and they don't have libraries they depend on and work out of the box on chromeOS, should I include them in the script ?
This would stop us from having to rely on emerge in order to get them (and thus save time)

**Comment by omgmog** [comment] 2015-02-19 16:16
Emerge solution is fine, if you're installing Arch Linux you're most likely going to be wiping your Chromebook, so the "mess" shouldn't be an issue. If you're using the script, then you're already saving yourself a lot of time :D

**Comment by jman6495** [comment] 2015-02-19 16:23
Ok ! I've added that, Will merge modifications ASAP and close this issue !

**Comment by jman6495** [comment] 2015-02-19 16:25
#30
Issue Resolved

**Comment by duck** [comment] 2015-02-19 16:26
Don't forget to update the README.md file...

**Closed by jman6495** 2015-02-19 16:25 UTC

**Comment by jman6495** [comment] 2015-02-19 16:36
@duck  will do once i've tested it on a vanilla chromebook install with dev mode, i want to be sure it works

**Comment by elkhunter** [comment] 2015-02-22 15:45
I downloaded the latest version and tried again but it still failed for me.  The sript appeared to run OK (except for some BINHOST errors during install which shouldn't matter), however when I tried to boot from it the device just gave one long beep.  I then booted back into Chromeos to try it with a different usb stick but the script reported it couldn't find the parted shared-lib and exited.

**Comment by jman6495** [comment] 2015-02-22 21:38
@elkhunter  are you sure you've disabled code signing and enabled USB boot ?
there should be some form of onscreen output (console) giving information about it.

**Comment by elkhunter** [comment] 2015-02-23 01:43
I have dev_boot_usb=1 and dev_boot_signed_only=0 and it will boot a ways using the dd image posted earlier in this thread but then crashes with same errors @duck captured in his screen dump above.  If I run the script to create the usb image it wont boot from it.  Instead it just beeps.  When I reboot into chrome to try it a 2nd time (with a different usb stick) it reports:
parted: error while loading shared libraries: libparted.so.2: cannot open shared object file: No such file or directory.

**Comment by jman6495** [comment] 2015-02-25 14:23
That's really weird ... Usually parted gets installed before launch.
try doing this : 
> sudo su -

then cd to your directory and run the script, sometimes when sudo'ing the script doesn't complete succesfully

**Comment by ahmetkadiraksoy** [comment] 2015-05-11 04:27
Hi. I just got a G2 (I guess) just like @duck. I can't seem to neither install the image on to a usb, nor boot from it. The installation on the usb stick gets stuck (at the screen shown in the image) and reboots the device. When I hit Ctrl+U, it makes a beep sound comes back to the initial screen without booting into usb. I was wondering if anyone was able to succeed?
![file may 10 9 07 29 pm](https://cloud.githubusercontent.com/assets/12388675/7558530/51d9df3e-f75b-11e4-89f2-60467954cd28.jpeg)

**Comment by duck** [comment] 2015-05-11 11:11
The only suggestion I have is to try a few different USB thumb-drives until you get one that works.  Getting a larger one might also help.  I have a few thumb-drives which I use all the time to boot x86 boxes from, but my Chromebook flatly refuses to successfully boot from them.  Once I switched USB media, it worked like a champ!

duck

**Comment by ahmetkadiraksoy** [comment] 2015-05-12 04:44
Thanks @duck. I tried quite a few different usb drives in different sizes. I finally gave up and returned it :) I might get something that is more compatible with running a native linux distro.

**Comment by starkers** [comment] 2015-05-12 14:36
I tried with easily half a dozen different ones before I gave up (although I'm up for trying again now)

..I'd like to put this to bed, if anyone could list known USB keys that will work I will try to buy one/some and test against them.

A pre-made dd image would help also :-)

**Comment by elkhunter** [comment] 2015-05-12 23:33
I tried 4 or 5 different usb devices also and never could get it to boot either.

**Comment by duck** [comment] 2015-05-13 00:55
This one worked for me:
[1604658.689874] usb 3-2: new high-speed USB device number 31 using xhci_hcd
[1604658.865873] usb-storage 3-2:1.0: USB Mass Storage device detected
[1604658.865950] scsi host13: usb-storage 3-2:1.0
[1604659.868034] scsi 13:0:0:0: Direct-Access     hp       v115w            0.00 PQ: 0 ANSI: 2
[1604659.869078] sd 13:0:0:0: [sdg] 7892992 512-byte logical blocks: (4.04 GB/3.76 GiB)

**Comment by duck** [comment] 2015-05-13 00:59
This one worked for me:
````
[1604658.689874] usb 3-2: new high-speed USB device number 31 using xhci_hcd
[1604658.865873] usb-storage 3-2:1.0: USB Mass Storage device detected
[1604658.865950] scsi host13: usb-storage 3-2:1.0
[1604659.868034] scsi 13:0:0:0: Direct-Access     hp       v115w            0.00 PQ: 0 ANSI: 2
[1604659.869078] sd 13:0:0:0: [sdg] 7892992 512-byte logical blocks: (4.04 GB/3.76 GiB)
```

I think you can still get these...I got it from work. Sorry.

d
